quickclash:
  #Language：
  #"ara":   "العربية"
  #"de":    "Deutsch"
  #"en":    "English"
  #"fra":   "français"
  #"jp":    "日本語"
  #"kor":   "한국어"
  #"ru":    "русский"
  #"th":    "ภาษาไทย"
  #"zh-CN": "简体中文"
  #"zh-TW": "繁體中文"
  lang: zh-CN
  #sublink可留空，但需要在程序运行时手动输入
  sublink: 
  #WebUI的端口
  port: 80
  #secret可为空
  secret: 123456
  #填写 clash 或 clash.meta
  core: clash.meta